project:
  type: website

website:
  favicon: assets/img/keyboard.png
  title: "Tony's Blog"
  site-url: https://tonyelhabr.rbind.io
  repo-url: https://github.com/tonyelhabr/itsmetoeknee
  google-analytics: '368311330'
  navbar:
    background: '#1c1c1c'
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
    right:
      - icon: github
        aria-label: github
        href: https://github.com/tonyelhabr
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/TonyElHabr
        
  twitter-card:
    site: '@TonyElHabr'

format:
  html:
    theme:
      light: [flatly, styles.css]
      dark: [darkly, styles.css]
    toc: true



