---
title: 'Projects'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{=html}
<style>
d-article li {
    margin-bottom: 0em;
    margin-left: 0;
    padding-left: 0;
}
</style>
```
-   2022 Carnegie Melon Sports Analytics Conference (CMSAC) Research Paper: Pending

-   ["Bundesliga tax" analysis](https://twitter.com/TonyElHabr/status/1405946563260817412) cited in [The Athletic](https://theathletic.com/3307533/2022/05/16/a-case-against-erling-haalands-move-to-manchester-city/), [Tifo Football](https://www.youtube.com/watch?v=07gDK0_Ea1U), [ESPN](https://www.espn.com/sports/insider/soccer/insider/story/_/id/34373375/bayern-munich-bundesliga-does-german-soccer-weirdness-hurt-dominant-team), [Grace Robertson](https://onfootball.substack.com/p/is-the-bundesliga-tax-real), and more.

-   [2021 Big Data Bowl (Big Data Bowl)](https://operations.nfl.com/gameday/analytics/big-data-bowl/) team submission ([finalist](https://www.youtube.com/watch?v=l-O24EqD4YI)) \| ["Weighted Assessment of Defender Affectiveness (WADE)"](https://www.kaggle.com/asmaetoumi/weighted-assessment-of-defender-effectiveness): A framework for quantifying NFL defensive back coverage and contest skills.

-   [2021 BDB](https://operations.nfl.com/gameday/analytics/big-data-bowl/) individual submission \| ["Assessing Pick Plays and How They're Defended"](https://www.kaggle.com/anthonyelhabr/assessing-pick-plays-and-how-they-re-defended): Quantifying the causal impact of pick routes run by NFL receivers using tracking data.

-   [Sports analytics visualization gallery](https://github.com/tonyelhabr/sports_viz): A collection of visualizations (mostly soccer and basketball) that I've tweeted out on a semi-weekly basis.

-   [{xengagement}](https://github.com/tonyelhabr/xengagement): An R package, Twitter bot, and python Dash app for predicting, visualizing, and summarizing the amount of Twitter engagement that [xGPhilosophy](https://twitter.com/xGPhilosophy) receives with its end-of-match xG summary tweets.

-   [NBA Regularized Adjusted Plus Minus (RAPM)](https://github.com/tonyelhabr/nba-rapm): Code for calculating RAPM given cleaned NBA play-by-play data.
