## Packages

-   I co-maintain [`{worldfootballR}`](https://github.com/JaseZiv/worldfootballR), an R package for extracting world football (soccer) data from several sites. I work mostly with the [Fotmob](https://www.fotmob.com/) functions. (Removed as of August 2023.)
-   I contributed functions for scraping data from [ESPN](https://www.espn.com/) to [`{ffscrapr}`](https://github.com/ffverse/ffscrapr/), an R API client for several fantasy football league platforms.
-   I wrote [`{valorantr}`](https://github.com/tonyelhabr/valorantr), an R package for pro Valorant data from [rib.gg](https://rib.gg/).

## Projects

-   [Sports analytics visualization gallery](https://github.com/tonyelhabr/sports_viz)
    -   A collection of visualizations (mostly soccer) that I've posted on social media.
-   ["Bundesliga tax" analysis](https://twitter.com/TonyElHabr/status/1405946563260817412)
    -   Cited in [The Athletic](https://theathletic.com/3307533/2022/05/16/a-case-against-erling-haalands-move-to-manchester-city/), [Tifo Football](https://www.youtube.com/watch?v=07gDK0_Ea1U), [ESPN](https://www.espn.com/sports/insider/soccer/insider/story/_/id/34373375/bayern-munich-bundesliga-does-german-soccer-weirdness-hurt-dominant-team), [Grace Robertson](https://onfootball.substack.com/p/is-the-bundesliga-tax-real), and more
-   [2021 Big Data Bowl (Big Data Bowl)](https://operations.nfl.com/gameday/analytics/big-data-bowl/) team submission ([finalist](https://www.youtube.com/watch?v=l-O24EqD4YI))
    -   ["Weighted Assessment of Defender Affectiveness (WADE)"](https://www.kaggle.com/asmaetoumi/weighted-assessment-of-defender-effectiveness): A framework for quantifying NFL defensive back coverage and contest skills
-   [2021 BDB](https://operations.nfl.com/gameday/analytics/big-data-bowl/) individual submission
    -   ["Assessing Pick Plays and How They're Defended"](https://www.kaggle.com/anthonyelhabr/assessing-pick-plays-and-how-they-re-defended): Quantifying the causal impact of pick routes run by NFL receivers using tracking data
-   [2022 Carnegie Melon Sports Analytics Conference (CMSAC)](https://www.stat.cmu.edu/cmsac/conference/2022/) paper
    -   [*"The Hot Hand Fallacy in Call of Duty Search and Destroy"*](https://github.com/tonyelhabr/cod_snd/blob/master/paper/paper.pdf)
-   [{xengagement}](https://github.com/tonyelhabr/xengagement)
    -   An R package, Twitter bot, and python Dash app for predicting, visualizing, and summarizing the amount of Twitter engagement that [xGPhilosophy](https://twitter.com/xGPhilosophy) receives with its end-of-match xG summary tweets
-   [NBA win probability](https://github.com/tonyelhabr/nba_wp)
    -   Code for calculating NBA win probability and discussion (8-hour interview project)
-   [NBA Regularized Adjusted Plus Minus (RAPM)](https://github.com/tonyelhabr/nba-rapm)
    -   Code for calculating RAPM given cleaned NBA play-by-play data
